{
  imports = [
    ./3dprint.nix
    ./alacritty.nix
    ./anki.nix
    ./calibre.nix
    ./digikam.nix
    ./eww
    ./filebrowser.nix
    ./git.nix
    ./hyprlock.nix
    ./imv.nix
    ./inkscape.nix
    ./libreoffice.nix
    ./messenger.nix
    ./nixvim
    ./picard.nix
    ./prismlauncher.nix
    ./pulseaudio
    ./river
    ./rofi
    ./skanlite.nix
    ./spotify.nix
    ./taskwarrior
    ./thunderbird.nix
    ./vlc.nix
    ./vscode.nix
    ./zathura.nix
    ./zoom.nix
    ./zsh.nix
    ./zk.nix
  ];
}
